apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: LoadBalancer
  loadBalancerIP: 149.165.168.38
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 8080
  selector:
    service: ambassador