apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  name: ${artifactId}-ingress-grpc
spec:
  rules:
     - host: custos.scigap.org
       http:
        paths:
          - path: /org.apache.custos.resource.secret.management.service.ResourceSecretManagementService(/|$)(.*)
            backend:
              serviceName: resource-secret-management-service
              servicePort: grpc

  tls:
    - hosts:
        - custos.scigap.org
      secretName: tls-secret