---

user: airavata
group: airavata
user_home: "/home/{{ user }}"

# Database related variables
db_server: "{{ groups['database'][0] }}"
db_server_port: "3306"
db_user: "airavata"
db_password: "{{ vault_db_password }}"
mysql_root_password: "{{ vault_mysql_root_password }}"

# Keycloak
keycloak_ssl_keystore_file: "{{ inventory_dir }}/files/keycloak.jks"
keycloak_ssl_keystore_password: "{{ vault_keycloak_ssl_keystore_password }}"
keycloak_db_host: "{{ groups['database'][0] }}"
keycloak_db_username: "keycloak"
keycloak_db_password: "{{ vault_keycloak_db_password }}"
keycloak_master_account_username: "admin"
keycloak_master_account_password: "{{ vault_keycloak_master_account_password }}"
...