apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  name: ${artifactId}-ingress-grpc
spec:
  rules:
     - http:
        paths:
          - backend:
              serviceName: tenant-management-service
              servicePort: grpc